"""A2A executor bridge used by Agent Runtime's A2aAgent template."""

import os
from typing import NoReturn

import vertexai
from a2a.server.agent_execution import AgentExecutor, RequestContext
from a2a.server.events import EventQueue
from a2a.server.tasks import TaskUpdater
from a2a.types import TaskState, TextPart, UnsupportedOperationError
from a2a.utils.errors import ServerError
from a2a.utils.message import new_agent_text_message
from google.adk.artifacts import InMemoryArtifactService
from google.adk.memory.in_memory_memory_service import InMemoryMemoryService
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService, VertexAiSessionService
from google.genai import types

from .agent import root_agent


class ClinicalOrchestratorExecutor(AgentExecutor):
    """Bridge A2A requests to the ADK root agent."""

    def __init__(self) -> None:
        self.agent = None
        self.runner = None

    def _init_agent(self) -> None:
        if self.agent is not None:
            return

        self.agent = root_agent
        engine_id = os.environ.get("GOOGLE_CLOUD_AGENT_ENGINE_ID")
        if engine_id:
            project = os.environ.get("GOOGLE_CLOUD_PROJECT")
            location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
            vertexai.init(project=project, location=location)
            session_service = VertexAiSessionService(
                project=project,
                location=location,
                agent_engine_id=engine_id,
            )
            app_name = engine_id
        else:
            session_service = InMemorySessionService()
            app_name = self.agent.name

        self.runner = Runner(
            app_name=app_name,
            agent=self.agent,
            artifact_service=InMemoryArtifactService(),
            session_service=session_service,
            memory_service=InMemoryMemoryService(),
        )

    async def execute(
        self, context: RequestContext, event_queue: EventQueue
    ) -> None:
        if self.runner is None:
            self._init_agent()

        query = context.get_user_input()
        updater = TaskUpdater(event_queue, context.task_id, context.context_id)
        user_id = (
            context.message.metadata.get("user_id", "a2a-user")
            if context.message and context.message.metadata
            else "a2a-user"
        )
        if not context.current_task:
            await updater.submit()
        await updater.start_work()

        try:
            session = await self._get_or_create_session(
                context.context_id, user_id
            )
            content = types.Content(
                role="user", parts=[types.Part(text=query)]
            )

            final_text_accumulator = []

            async for event in self.runner.run_async(
                session_id=session.id,
                user_id=user_id,
                new_message=content,
            ):
                if event.content and event.content.parts:
                    for part in event.content.parts:
                        if getattr(part, "text", None):
                            final_text_accumulator.append(part.text)

            final_response = "".join(final_text_accumulator).strip()
            if not final_response:
                final_response = "No response generated by clinical orchestrator."

            await updater.add_artifact(
                [TextPart(text=final_response)], name="answer"
            )
            await updater.complete()

        except Exception as exc:
            await updater.update_status(
                TaskState.failed,
                message=new_agent_text_message(f"Error: {exc!s}"),
            )
            raise

    async def _get_or_create_session(self, context_id: str, user_id: str):
        app_name = self.runner.app_name
        if context_id:
            session = await self.runner.session_service.get_session(
                app_name=app_name,
                session_id=context_id,
                user_id=user_id,
            )
            if session:
                return session
        return await self.runner.session_service.create_session(
            app_name=app_name,
            user_id=user_id,
            session_id=context_id or None,
        )

    async def cancel(
        self, context: RequestContext, event_queue: EventQueue
    ) -> NoReturn:
        raise ServerError(error=UnsupportedOperationError())